<div class="postOverlayContainer">
    <div class="postOverlay overlayMsg">
        <img src="themes/default/images/loader.gif" alt="Bitte warten..." title="Bitte warten...">
        <br><br>
<pre id="overlay-output">Please wait...</pre>
        <script>
            $(document).ready (function(){
                setInterval(overlayoutput, 300);
            });
        </script>
    </div>
</div>

{{module::connector_cronjob_status}}

<div class="row mb-4">
    <div class="col-12 col-lg-8">
        {{module::connector_buttons}}
    </div>
    <div class="col-12 col-lg-4 mt-4 mt-lg-0">
        {{module::connector_singlesync}}
    </div>
</div>

<div class="row">
    <div class="col-12">
        {{module::connector_output}}
    </div>
</div>