<div id="accordion">

    <div class="card mb-2">
        <div class="card-header" id="help1rel">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#help1" aria-expanded="false" aria-controls="help1">
                    {{help_1_header}}
                </button>
            </h5>
        </div>
        <div id="help1" class="collapse" aria-labelledby="help1" data-parent="#accordion">
            <div class="card-body">
                {{help_1_text}}
            </div>
        </div>
    </div>
    
    <div class="card mb-2">
        <div class="card-header" id="help2rel">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#help2" aria-expanded="false" aria-controls="help2">
                    {{help_2_header}}
                </button>
            </h5>
        </div>
        <div id="help2" class="collapse" aria-labelledby="help2" data-parent="#accordion">
            <div class="card-body">
                {{help_2_text}}
            </div>
        </div>
    </div>
    
    <div class="card mb-4">
        <div class="card-header" id="help3rel">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#help3" aria-expanded="false" aria-controls="help3">
                    {{help_3_header}}
                </button>
            </h5>
        </div>
        <div id="help3" class="collapse" aria-labelledby="help3" data-parent="#accordion">
            <div class="card-body">
                {{help_3_text}}
            </div>
        </div>
    </div>
    
    <div class="card mb-2">
        <div class="card-header" id="help4rel">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#help4" aria-expanded="false" aria-controls="help4">
                    {{help_4_header}}
                </button>
            </h5>
        </div>
        <div id="help4" class="collapse" aria-labelledby="help4" data-parent="#accordion">
            <div class="card-body">
                {{help_4_text}}
            </div>
        </div>
    </div>
    
    <div class="card mb-2">
        <div class="card-header" id="help5rel">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#help5" aria-expanded="false" aria-controls="help5">
                    {{help_5_header}}
                </button>
            </h5>
        </div>
        <div id="help5" class="collapse" aria-labelledby="help5" data-parent="#accordion">
            <div class="card-body">
                {{help_5_text}}
            </div>
        </div>
    </div>
    
    <div class="card mb-2">
        <div class="card-header" id="help6rel">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#help6" aria-expanded="false" aria-controls="help6">
                    {{help_6_header}}
                </button>
            </h5>
        </div>
        <div id="help6" class="collapse" aria-labelledby="help6" data-parent="#accordion">
            <div class="card-body">
                {{help_6_text}}
            </div>
        </div>
    </div>
    
    <div class="card mb-4">
        <div class="card-header" id="help7rel">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#help7" aria-expanded="false" aria-controls="help7">
                    {{help_7_header}}
                </button>
            </h5>
        </div>
        <div id="help7" class="collapse" aria-labelledby="help7" data-parent="#accordion">
            <div class="card-body">
                {{help_7_text}}
            </div>
        </div>
    </div>
    
    <div class="card mb-4">
        <div class="card-header" id="help8rel">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#help8" aria-expanded="false" aria-controls="help8">
                    {{help_8_header}}
                </button>
            </h5>
        </div>
        <div id="help8" class="collapse" aria-labelledby="help8" data-parent="#accordion">
            <div class="card-body">
                {{help_8_text}}
            </div>
        </div>
    </div>
    
    <div class="card mb-2">
        <div class="card-header" id="help9rel">
            <h5 class="mb-0">
                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#help9" aria-expanded="false" aria-controls="help9">
                    {{help_9_header}}
                </button>
            </h5>
        </div>
        <div id="help9" class="collapse" aria-labelledby="help9" data-parent="#accordion">
            <div class="card-body">
                {{help_9_text}}
            </div>
        </div>
    </div>
    
</div>