{{module::connector_cronjob_status}}

<div class="row">
    <div class="col-12 col-lg-6 mb-4">
        {{module::systeminfo_load}}
    </div>
    <div class="col-12 col-md-6 col-lg-3 mb-4">
        {{module::systeminfo_shopwareversion}}
    </div>
    <div class="col-12 col-md-6 col-lg-3 mb-4">
        {{module::systeminfo_connectorversion}}
    </div>
    <div class="col-12 col-md-6 col-lg-3 mb-4">
        {{module::systeminfo_php}}
    </div>
    <div class="col-12 col-md-6 col-lg-3 mb-4">
        {{module::systeminfo_database}}
    </div>
    <div class="col-12 col-md-6 col-lg-3 mb-4">
        {{module::systeminfo_webserver}}
    </div>
    <div class="col-12 col-md-6 col-lg-3 mb-4">
        {{module::systeminfo_time}}
    </div>
    <div class="col-12 col-lg-8 mb-4">
        {{module::systeminfo_phpextensions}}
    </div>
    <div class="col-12 col-lg-4 mb-4">
        {{module::systeminfo_phpini}}
    </div>
</div>

<div class="row text-center">
    <div class="col-12">
        <small>
            PSC7-Helper {{version}}
        </small>
    </div>
</div>