<div class="card">
    <div class="card-body console-stream">
        <div class="embed-responsive embed-responsive-21by9">
            <iframe id="outputframe" class="embed-responsive-item" src="ajax.php?type=m&amp;n=connector_output&amp;a=iframe" scrolling="yes"></iframe>
            <script type="text/javascript">
		var timer;
    
                autoScroll();
                
                function autoScroll() {
			var frame = document.getElementById('outputframe').contentWindow;
			frame.scrollTo(0, 1000000);
			timer = setTimeout('autoScroll()', 100);
		}
                
                function clearAutoScroll() {
                    clearTimeout(timer);
                    return;
		}
            </script>
        </div>
        <a href="#outputframe" onclick="javascript:clearAutoScroll();" title="Auto-Scroll beenden">Auto-Scroll beenden</a>
    </div>
</div>