<div class="card h-100">
    <div class="card-header">
        <h5>
            {{cardtitle}}
        </h5>
    </div>
    <div class="card-body">
        <script>
            var singlesyncItems = {{jsArrayItems}};
            $(document).ready (function(){
                autocomplete(document.getElementById("singlesyncItems"), singlesyncItems);
            });
        </script>
        <form action="{{formaction}}" method="post" autocomplete="off">
            <input type="hidden" name="formname" value="clicommand">
            <input type="hidden" name="formkey" value="{{formkey}}">
            <input type="hidden" name="formsecret" value="">
            <input type="hidden" name="command" value="singlesync">
            <input type="hidden" name="option_all" value="0">
            <input type="hidden" name="option_vvv" value="1">
            <input type="hidden" name="option_backlog" value="1">
            <div class="form-row">
                <div class="col mb-1">
                    <div class="form-group">
                        <label for="product">{{product_label}}</label>
                        <input id="singlesyncItems" class="form-control input-autocomplete" type="text" name="product" value="" placeholder="{{product_placeholder}}" required>
                    </div>
                </div>
            </div>
            <button class="btn btn-psc7" type="submit">{{btn_text}}</button>
        </form>
    </div>
</div>