<div class="postOverlayContainer">
    <div class="postOverlay overlayMsg">
        <div class="pb-4">
            <img src="themes/default/images/loader.gif" alt="Please wait..." title="Please wait...">
        </div>
        <span>
            Please wait...
        </span>
    </div>
</div>

<div class="row mb-4">
    <div class="col-12">
        {{module::connector_output}}
    </div>
</div>

<div class="row">
    <div class="col-12">
        {{module::tools_articlestatus}}
    </div>
</div>