<div class="alert alert-danger mb-4">
    <form style="float:right; width: 40px;" action="{{formaction}}" method="post">
        <input type="hidden" name="formname" value="cronjobstatus">
        <input type="hidden" name="formkey" value="{{formkey}}">
        <input type="hidden" name="formsecret" value="">
        <button type="submit" class="close" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </form>
    {{alert}}
</div>