<div class="card h-100">
    <div class="card-header">
        <h5>
            {{cardtitle}}
        </h5>
    </div>
    <div class="card-body text-center">
        <i class="far fa-clock fa-beat"></i> <span id="systeminfo-time">{{time}}</span>
        <script>
            $(document).ready (function(){
                setInterval(systeminfoTime, 3000);
            });
        </script>
    </div>
</div>