<div class="card">
    <div class="card-header">
        <h5>
            {{cardtitle}}
        </h5>
    </div>
    <div class="card-body text-center">
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="info.php">
                {{noiframe}}
                <br><a href="{{noiframe_link}}" title="" target="_new">{{noiframe_text}}</a>
            </iframe>
        </div>
    </div>
</div>