<div class="card">
    <div class="card-header">
        <h5>
            {{cardtitle}}
        </h5>
    </div>
    <div class="card-body">
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="info.php"></iframe>
        </div>
        <br><a href="{{noiframe_link}}" title="{{noiframe_text}}" target="_blank">{{noiframe_text}}</a>
    </div>
</div>