<div class="card h-100">
    <div class="card-header">
        <div class="float-right font-size-min pt-2">
        </div>
        <h5>
            {{cardtitle}}
        </h5>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12 mb-4">
                <div id="backlogcount">
                    {{backlogcount}}
                </div>
                <script>
                    $(document).ready (function(){
                        setInterval(backlogcount, 10000);
                    });
                </script>
            </div>
            <div class="col-12 col-sm-6 mb-4">
                {{ordercount}}
            </div>
            <div class="col-12 col-sm-6 mb-4">
                {{productcount}}
            </div>
            <div class="col-12 col-sm-6 mb-4">
                {{variationcount}}
            </div>
            <div class="col-12 col-sm-6 mb-4">
                {{mediacount}}
            </div>
            <div class="col-12 col-sm-6">
                {{categorycount}}
            </div>
            <div class="col-12 col-sm-6 mt-4 mt-sm-0">
                {{manufacturercount}}
            </div>
        </div>
    </div>
</div>