<div class="card mb-4">
    <div class="card-header">
        <h5>
            {{cardtitle}}
        </h5>
    </div>
    <div class="card-body">
        <form action="{{formaction}}" method="post">
            <input type="hidden" name="formname" value="logfile">
            <input type="hidden" name="formkey" value="{{formkey}}">
            <input type="hidden" name="formsecret" value="">
            <div class="form-row">
                <div class="col-12 col-md-6">
                    <div class="form-group mb-4">
                        <label for="logfile">{{logfile_label}}</label>
                        <select class="form-control" id="logfile" name="logfile_file">
                            {{logfile_options}}
                        </select>
                        <small id="logfile_help" class="form-text text-muted">
                            {{logfile_help}}
                        </small>
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <div class="form-group mb-4">
                        <label for="filter">{{filter_label}}</label>
                        <select class="form-control" id="value" name="logfile_filter">
                            {{filter_list}}
                        </select>
                        <small id="filter_help" class="form-text text-muted">
                            {{filter_help}}
                        </small>
                    </div>
                </div>
            </div>
            <button class="btn btn-psc7" type="submit">{{btn_text}}</button>
        </form>
    </div>
</div>

<div class="card">
    <div class="card-body console-stream">
        {{file_stream}}
    </div>
</div>